// This file is @generated by prost-build.
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cookie {
    ///
    #[prost(string, tag = "1")]
    pub region_token: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub extra: ::prost::alloc::string::String,
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Debug {
    ///
    #[prost(string, tag = "1")]
    pub ip_region: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub app_lang: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub app_region: ::prost::alloc::string::String,
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    ///
    #[prost(string, tag = "1")]
    pub country_code: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub currency_code: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub market: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub idfa: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub gps_adid: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub android_id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "7")]
    pub idfv: ::prost::alloc::string::String,
}
///
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerParams {
    ///
    #[prost(int32, tag = "1")]
    pub prefer_code_type: i32,
    ///
    #[prost(int32, tag = "2")]
    pub user_qn: i32,
    ///
    #[prost(int64, tag = "3")]
    pub fnval: i64,
    ///
    #[prost(int64, tag = "4")]
    pub fnver: i64,
}
